smallrye:
  jwt:
    sign:
      key:
        location: ${AUTH_PRIVATE_KEY}

mp:
  jwt:
    verify:
      issuer: Issuer
      publickey:
        location: ${AUTH_PUBLIC_KEY}

quarkus:
  http:
    auth:
      proactive: false

  native:
    resources:
      includes: ${AUTH_PUBLIC_KEY}

  flyway:
    migrate-at-start: true

  datasource:
    db-kind: postgresql
    username: postgres
    password: secret
    jdbc:
      url: jdbc:postgresql://localhost:5432/quarkus
      max-size: 200